### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by takahashir986** [Yan98/Event-Camera-Data-Pre-training#4]
Hi, thank you for sharing your great work!

Could you tell me what license is applied to this repo?

Thank you.

**Comment by Yan98** [comment]
Hi,

This work is under the [Attribution-NonCommercial-NoDerivs 4.0 International](https://creativecommons.org/licenses/by-nc-nd/4.0/).

**Comment by takahashir986** [comment]
Thank you!
